feat: dynamic fields
kgolezardi/Performance-Review-Web pull request #415
Opened 2022-07-20 11:28 UTC by mdeljavan

2022-07-23 12:16 UTC, mh-alahdadian requested changes

2022-07-23 12:16 UTC, mh-alahdadian commented on src/shared/forminator/DynamicFields/MultipleSelectQuestion.tsx
> +      {helpText && (
move helpText to textField

2022-07-23 12:16 UTC, mh-alahdadian commented on src/shared/forminator/__stories__/FiledRenderer.stories.tsx
> +const questions: QuestionType[] = [
why QuestionType ?

2022-07-23 12:16 UTC, mh-alahdadian commented on src/shared/forminator/index.ts
> +export type { Question as QuestionType } from './DynamicFields/DynamicFields';
use IQuestion or QuestionInterface

2022-07-23 12:16 UTC, mh-alahdadian commented on src/shared/project-output/AnswerOutput.tsx
> +  const answer = answers.find((ans) => ans.questionId === questionId);
try move this logic out

2022-07-23 12:16 UTC, mh-alahdadian commented on src/shared/project-output/AnswerOutput.tsx
> +  return <MultilineOutput value={text ?? null} enableTruncating />;
you might use this directly

2022-07-24 07:42 UTC, mh-alahdadian requested changes

2022-07-24 07:42 UTC, mh-alahdadian commented on src/core/domain/Question.ts
> +  readonly privateAnswerToPeerReviewers: boolean;
remove these booleans if you don't use them

2022-07-24 07:42 UTC, mh-alahdadian commented on src/pages/manager-review-page/achievements/ManagerReviewAchievementsRatingGroup.tsx
> +  const filteredByRating = comments.filter((comment) => comment.rating === rating);
what happened to rest of the logic ?

2022-07-24 07:42 UTC, mh-alahdadian commented on src/shared/forminator/utils/FragmentPrompt.ts
> +  console.log(value, props.value, when);
remove

2022-07-24 07:42 UTC, mh-alahdadian commented on src/shared/forminator/inputs/SelectMultiAutoComplete.tsx
> +  textFieldOptions?: Omit<OutlinedTextFieldProps, 'variant'>;
why not TextFieldProps instead ?

2022-07-24 07:42 UTC, mh-alahdadian commented on src/shared/utils/questionsAnswersPair.ts
> +  return [...questions].map((question) => {
questions.map

2022-07-24 07:42 UTC, mh-alahdadian commented on src/shared/utils/transformAnswers.ts
> +  return Object.entries(ans).reduce<Answer[]>((acc, [key, value]) => {
use old version like this 
`Object.entries(ans).filter(value).map`

2022-07-24 07:42 UTC, mh-alahdadian commented on src/shared/utils/transformAnswers.ts
> +    const question = [...questions].find((q) => q.id === curr.questionId);
questions.find

2022-07-24 10:08 UTC, mdeljavan commented on src/pages/manager-review-page/achievements/ManagerReviewAchievementsRatingGroup.tsx
> +  const filteredComments = filteredByRating.filter((comment) => peerAnswers(comment.answers).every(prop('value')));
no. revert

2022-07-24 11:33 UTC, mehrdad-e approved these changes

2022-07-24 11:36 UTC, merged